---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[zfs_linux::default]
      - recipe[zfs_linux-test::default]
    attributes:
      dev_mode: true
  - name: source
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[apt]
      - recipe[zfs_linux::source]
      - recipe[zfs_linux-test::default]
    attributes:
      dev_mode: true
